Repository netlify/netlify-plugin-lighthouse, pull requests merged in 2022-09, with the labels that each got.

#461 feat: Add support for theme matching and scroll reporting via `postMessage`
  src/replacements.js
  src/replacements.test.js
Labels: type: feature

#469 fix: run replacements function before HTML minification
  src/index.js
Labels: type: bug

#467 Add example showing multiple site paths support in README.md
  README.md
Labels: type: chore

#473 Adds score rounding to avoid floating point errors
  src/index.js
Labels: type: bug

#474 Pass (selected) Lighthouse settings via netlify.toml
  .env.example
  .gitignore
  README.md
  manifest.yml
  src/index.js
  src/lighthouse.js
  src/settings.js
  src/settings.test.js
Labels: type: feature

#476 Adds a check for the 'installable-manifest' audit score
  src/index.js
Labels: type: feature
