Repository netlify/netlify-plugin-lighthouse, pull requests merged in 2022-07, with the labels that each got.

#422 feat: upgrade Lighthouse and node
  .github/workflows/test.yml
  netlify.toml
  package-lock.json
  package.json
Labels: type: chore, type: feature

#426 chore: update repository url in package.json
  package.json
Labels: type: chore, type: bug

#429 chore: update workflow secrets naming
  .github/workflows/release-please.yml
Labels: type: chore

#428 chore: add workflow step to publish to npm and plugins
  .github/workflows/release-please.yml
  release.config.js
Labels: type: chore

#430 fix: update changelog to reflect already released
  CHANGELOG.md
Labels: type: bug

#433 chore: remove non-existent working directory from workflow
  .github/workflows/release-please.yml
Labels: type: chore

#439 fix: specify node version `>=14.15 <18`
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: type: bug

#445 chore: update release process in contributing docs
  CONTRIBUTING.md
Labels: type: chore

#440 feat: extract the full html report
  package-lock.json
  package.json
  src/index.js
Labels: type: feature, echoes/intent: customer-value
