Repository netlify/netlify-plugin-lighthouse, pull requests merged in 2022-10, with the labels that each got.

#479 feat: send reports on threshold failure
  src/index.js
Labels: type: feature

#483 Reduce scope of 'installable' test
  src/index.js
Labels: type: feature

#485 Capitalize Lighthouse
  README.md
Labels: type: chore

#477 Add support for Desktop device, other languages, and some other clarity tidying
  README.md
Labels: type: chore

#492 chore: remove log line
  src/index.js
Labels: type: chore

#509 fix(docs): fix broken links and content flow
  README.md
Labels: area: docs
